name: CI-CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t temade91/netflix-clone:latest .

      - name: Push Docker Image
        run: docker push temade91/netflix-clone:latest

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.0
        with:
           host: ${{ secrets.SERVER_IP }}
           username: ${{ secrets.SERVER_USER }}
           password: ${{ secrets.SERVER_PASSWORD }}
           script: |
             set -e

             SERVICE_NAME=netflix-clone
             PARENT_DIR=~/project-folder

             mkdir -p $PARENT_DIR

             mkdir -p $PARENT_DIR/$SERVICE_NAME

             cd $PARENT_DIR/$SERVICE_NAME

             if [ -f docker-compose.yml ]; then cp docker-compose.yml docker-compose.yml.bak; fi

             curl -L https://raw.githubusercontent.com/temade91/test-project/feature/docker-compose.yml -o docker-compose.yml

             docker compose pull

             docker compose up -d
